replicaCount: 1

nameOverride: "wdb-maintenance"
fullnameOverride: "wdb-maintenance"

image:
  repository: docker.pkg.github.com/sullrich84/wettkampfdb-maintenance/wdb-maintenance
  pullPolicy: Always
  debug: true
  tag: latest

imagePullSecrets:
  - name: registry-cred

containerPorts:
  - name: http
    containerPort: 80
    protocol: TCP

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  failureThreshold: 5
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  failureThreshold: 5
  periodSeconds: 5

serviceAccount:
  create: true
  name: "wdb-maintenance-service-user"
  annotations: {}

service:
  type: ClusterIP

podSecurityContext:
  runAsUser: 0

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

podAnnotations: {}
securityContext: {}
resources: {}
nodeSelector: {}
affinity: {}
tolerations: {}
