{{- $appName := include "app.fullname" . -}}
{{- $servicePort := (index .Values.containerPorts (index .Values.ingress.targetPortName)).containerPort -}}

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: '''"true"'''
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - backend:
            serviceName: {{ $appName }}
            servicePort: {{ $servicePort }}
    {{- if .Values.ingress.www }}
    - host: www.{{ .Values.ingress.host }}
      http:
        paths:
        - backend:
            serviceName: {{ $appName }}
            servicePort: {{ $servicePort }}
    {{- end }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.host | replace "." "-" }}-secret
    {{- if .Values.ingress.www }}
    - hosts:
      - www.{{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.host | replace "." "-" }}-secret
    {{- end }}
{{- end }}