# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.containerPorts }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .name }}
    {{- end }}
  selector: {{- include "app.selectorLabels" . | nindent 4 }}
