replicaCount: 1

nameOverride: "wdb-maintenance"
fullnameOverride: "wdb-maintenance"

image:
  repository: ghcr.io/sullrich84/wdb-maintenance
  pullPolicy: Always
  debug: true
  tag: latest

ingress:
  enabled: true
  targetPortName: http
  hosts:
    - maintenance.wettkampfdb.de
    - www.maintenance.wettkampfdb.de

imagePullSecrets:
  - name: registry-cred

containerPorts:
  http:
    name: http
    containerPort: 8080
    protocol: TCP

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  failureThreshold: 5
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  failureThreshold: 5
  periodSeconds: 5

serviceAccount:
  create: true
  name: "wdb-maintenance-service-user"
  annotations: {}

service:
  type: ClusterIP

podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

podAnnotations: {}
securityContext: {}
resources: {}
nodeSelector: {}
affinity: {}
tolerations: {}
