name: Build Latest

on:
  release:
    types: [published]

env:
  IMAGE_NAME: wdb-maintenance
  REPOSITORY_NAME: wettkampfdb-maintenance
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build . -t $IMAGE_NAME

      ###
      ### Runs the docker build command and uploads resulting images to GitHubs package registry.
      ###
      - name: Docker Push
        run: |
          docker login ghcr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag $IMAGE_NAME ghcr.io/sullrich84/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME ghcr.io/sullrich84/$IMAGE_NAME:$(git describe --abbrev=0 --tags)
          docker push -a ghcr.io/sullrich84/$IMAGE_NAME
